[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
    "pip install --no-cache-dir setuptools==69.0.0 wheel",
    "pip install --no-cache-dir -r requirements.txt --no-build-isolation"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8080"
